budzik:
  czasy:
    aktualnie: "zdalne"
    stacjonarne: ["0.08:00:00", "1.06:52:00", "2.06:52:00", "3.06:52:00", "4.06:52:00"]
    zdalne: ["0.09:45:00", "1.07:55:00", "2.07:55:00", "3.07:55:00", "4.07:55:00"]
  maxOptymalizacja: 0.75
  sleepDelay: 15
  ytLista: 
     - "https://www.youtube.com/watch?v=dQw4w9WgXcQ" # rick astley - never gonna give you up
led:
  port: "/dev/ttyUSB0"
  lat: 49.8
  lon: 19
  colors:
    highblue: "056232255"
    lowblue: "173058014"
  file: "/var/lib/docker/volumes/homeassistant/_data/sensor.txt"
holidays:
  holidaysStart: "23.12.2021"
  holidaysEnd: "02.01.2022"